// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: error_model_func_wrt_offset2
 *
 * Args:
 *     theta11: Scalar
 *     theta12: Scalar
 *     theta21: Scalar
 *     theta22: Scalar
 *     offset1: Scalar
 *     offset2: Scalar
 *     alpha: Scalar
 *     beta: Scalar
 *     RotGT1: Rot3
 *     RotGT2: Rot3
 *     RotHandEye: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix31
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 3, 1> ErrorModelFuncWrtOffset2(
    const Scalar theta11, const Scalar theta12, const Scalar theta21, const Scalar theta22,
    const Scalar offset1, const Scalar offset2, const Scalar alpha, const Scalar beta,
    const sym::Rot3<Scalar>& RotGT1, const sym::Rot3<Scalar>& RotGT2,
    const sym::Rot3<Scalar>& RotHandEye, const Scalar epsilon) {
  // Total ops: 882

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _RotGT1 = RotGT1.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _RotGT2 = RotGT2.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _RotHandEye = RotHandEye.Data();

  // Intermediate terms (256)
  const Scalar _tmp0 = _RotGT1[0] * _RotGT2[0] + _RotGT1[1] * _RotGT2[1] + _RotGT1[2] * _RotGT2[2] +
                       _RotGT1[3] * _RotGT2[3];
  const Scalar _tmp1 = -_RotGT1[0] * _RotGT2[3] - _RotGT1[1] * _RotGT2[2] +
                       _RotGT1[2] * _RotGT2[1] + _RotGT1[3] * _RotGT2[0];
  const Scalar _tmp2 = _RotGT1[0] * _RotGT2[2] - _RotGT1[1] * _RotGT2[3] - _RotGT1[2] * _RotGT2[0] +
                       _RotGT1[3] * _RotGT2[1];
  const Scalar _tmp3 = -_RotGT1[0] * _RotGT2[1] + _RotGT1[1] * _RotGT2[0] -
                       _RotGT1[2] * _RotGT2[3] + _RotGT1[3] * _RotGT2[2];
  const Scalar _tmp4 = _RotHandEye[0] * _tmp1 + _RotHandEye[1] * _tmp2 + _RotHandEye[2] * _tmp3 +
                       _RotHandEye[3] * _tmp0;
  const Scalar _tmp5 = -_RotHandEye[0] * _tmp2 + _RotHandEye[1] * _tmp1 - _RotHandEye[2] * _tmp0 +
                       _RotHandEye[3] * _tmp3;
  const Scalar _tmp6 = -_RotHandEye[0] * _tmp0 - _RotHandEye[1] * _tmp3 + _RotHandEye[2] * _tmp2 +
                       _RotHandEye[3] * _tmp1;
  const Scalar _tmp7 = _RotHandEye[0] * _tmp3 - _RotHandEye[1] * _tmp0 - _RotHandEye[2] * _tmp1 +
                       _RotHandEye[3] * _tmp2;
  const Scalar _tmp8 = _RotHandEye[0] * _tmp4 - _RotHandEye[1] * _tmp5 + _RotHandEye[2] * _tmp7 +
                       _RotHandEye[3] * _tmp6;
  const Scalar _tmp9 = std::sin(beta);
  const Scalar _tmp10 = Scalar(1.0) / (_tmp9);
  const Scalar _tmp11 = std::cos(alpha);
  const Scalar _tmp12 = _tmp11 + std::cos(beta);
  const Scalar _tmp13 = Scalar(1.0) / (_tmp12);
  const Scalar _tmp14 = std::pow(_tmp9, Scalar(2));
  const Scalar _tmp15 = std::sin(alpha);
  const Scalar _tmp16 = std::pow(_tmp15, Scalar(2));
  const Scalar _tmp17 = offset2 + theta22;
  const Scalar _tmp18 = offset1 + theta21;
  const Scalar _tmp19 = -Scalar(1) / Scalar(2) * _tmp17 + (Scalar(1) / Scalar(2)) * _tmp18;
  const Scalar _tmp20 = std::sin(_tmp19);
  const Scalar _tmp21 = std::sqrt(Scalar(_tmp14 - _tmp16 * std::pow(_tmp20, Scalar(2))));
  const Scalar _tmp22 = std::cos(_tmp19);
  const Scalar _tmp23 = _tmp15 * _tmp22 + _tmp21;
  const Scalar _tmp24 = 2 * std::atan(_tmp13 * _tmp23);
  const Scalar _tmp25 = std::cos(_tmp24);
  const Scalar _tmp26 = _tmp15 * std::sin(_tmp18);
  const Scalar _tmp27 = _tmp25 * _tmp26;
  const Scalar _tmp28 = (Scalar(1) / Scalar(2)) * _tmp17 + (Scalar(1) / Scalar(2)) * _tmp18;
  const Scalar _tmp29 = std::sin(_tmp28);
  const Scalar _tmp30 = std::sin(_tmp24);
  const Scalar _tmp31 = _tmp11 * _tmp30;
  const Scalar _tmp32 = _tmp29 * _tmp31;
  const Scalar _tmp33 = _tmp27 - _tmp32;
  const Scalar _tmp34 = std::cos(_tmp28);
  const Scalar _tmp35 = _tmp26 * _tmp30;
  const Scalar _tmp36 = _tmp15 * std::cos(_tmp18);
  const Scalar _tmp37 = _tmp30 * _tmp36;
  const Scalar _tmp38 = _tmp29 * _tmp37 - _tmp34 * _tmp35;
  const Scalar _tmp39 = _tmp10 * (-_tmp11 * _tmp33 + _tmp36 * _tmp38);
  const Scalar _tmp40 = _tmp10 * _tmp33;
  const Scalar _tmp41 = _tmp39 + _tmp40;
  const Scalar _tmp42 = _tmp25 * _tmp36;
  const Scalar _tmp43 = _tmp31 * _tmp34;
  const Scalar _tmp44 = -_tmp42 + _tmp43;
  const Scalar _tmp45 = _tmp10 * _tmp44;
  const Scalar _tmp46 = _tmp10 * (_tmp11 * _tmp44 - _tmp26 * _tmp38);
  const Scalar _tmp47 = -_tmp46;
  const Scalar _tmp48 = -_tmp11;
  const Scalar _tmp49 = _tmp48 + 1;
  const Scalar _tmp50 = _tmp45 + _tmp47 + _tmp49;
  const Scalar _tmp51 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp50)));
  const Scalar _tmp52 = _tmp11 + _tmp46;
  const Scalar _tmp53 = _tmp45 + _tmp52;
  const Scalar _tmp54 =
      -std::max<Scalar>(_tmp11, std::max<Scalar>(_tmp45, std::max<Scalar>(_tmp46, _tmp53)));
  const Scalar _tmp55 =
      1 - std::max<Scalar>(0, -(((_tmp46 + _tmp54) > 0) - ((_tmp46 + _tmp54) < 0)));
  const Scalar _tmp56 = _tmp45 + _tmp54;
  const Scalar _tmp57 = std::min<Scalar>(
      1 - std::max<Scalar>(0, _tmp55), 1 - std::max<Scalar>(0, -(((_tmp56) > 0) - ((_tmp56) < 0))));
  const Scalar _tmp58 = _tmp51 - _tmp57 + 1;
  const Scalar _tmp59 = (Scalar(1) / Scalar(2)) * _tmp57;
  const Scalar _tmp60 = _tmp59 / _tmp58;
  const Scalar _tmp61 = _tmp10 * _tmp38;
  const Scalar _tmp62 = _tmp26 - _tmp61;
  const Scalar _tmp63 = _tmp53 + 1;
  const Scalar _tmp64 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp63)));
  const Scalar _tmp65 = std::min<Scalar>(
      1 - std::max<Scalar>(0, std::max<Scalar>(_tmp55, _tmp57)),
      1 - std::max<Scalar>(0, -(((_tmp11 + _tmp54) > 0) - ((_tmp11 + _tmp54) < 0))));
  const Scalar _tmp66 = std::min<Scalar>(
      1 - std::max<Scalar>(0, std::max<Scalar>(_tmp55, std::max<Scalar>(_tmp57, _tmp65))),
      1 - std::max<Scalar>(0, -(((_tmp52 + _tmp56) > 0) - ((_tmp52 + _tmp56) < 0))));
  const Scalar _tmp67 = _tmp64 - _tmp66 + 1;
  const Scalar _tmp68 = (Scalar(1) / Scalar(2)) * _tmp66;
  const Scalar _tmp69 = _tmp68 / _tmp67;
  const Scalar _tmp70 = -_tmp45;
  const Scalar _tmp71 = _tmp46 + _tmp49 + _tmp70;
  const Scalar _tmp72 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp71)));
  const Scalar _tmp73 = -_tmp55 + _tmp72 + 1;
  const Scalar _tmp74 = (Scalar(1) / Scalar(2)) * _tmp55;
  const Scalar _tmp75 = _tmp10 * (_tmp26 * _tmp33 - _tmp36 * _tmp44);
  const Scalar _tmp76 = _tmp36 + _tmp75;
  const Scalar _tmp77 = _tmp11 + _tmp47 + _tmp70 + 1;
  const Scalar _tmp78 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp77)));
  const Scalar _tmp79 = -_tmp65 + _tmp78 + 1;
  const Scalar _tmp80 = (Scalar(1) / Scalar(2)) * _tmp65;
  const Scalar _tmp81 = _tmp80 / _tmp79;
  const Scalar _tmp82 = _tmp41 * _tmp60 + _tmp62 * _tmp69 + _tmp73 * _tmp74 + _tmp76 * _tmp81;
  const Scalar _tmp83 = offset2 + theta12;
  const Scalar _tmp84 = offset1 + theta11;
  const Scalar _tmp85 = -Scalar(1) / Scalar(2) * _tmp83 + (Scalar(1) / Scalar(2)) * _tmp84;
  const Scalar _tmp86 = std::sin(_tmp85);
  const Scalar _tmp87 = std::sqrt(Scalar(_tmp14 - _tmp16 * std::pow(_tmp86, Scalar(2))));
  const Scalar _tmp88 = std::cos(_tmp85);
  const Scalar _tmp89 = _tmp15 * _tmp88 + _tmp87;
  const Scalar _tmp90 = 2 * std::atan(_tmp13 * _tmp89);
  const Scalar _tmp91 = std::cos(_tmp90);
  const Scalar _tmp92 = _tmp15 * std::sin(_tmp84);
  const Scalar _tmp93 = _tmp91 * _tmp92;
  const Scalar _tmp94 = (Scalar(1) / Scalar(2)) * _tmp83 + (Scalar(1) / Scalar(2)) * _tmp84;
  const Scalar _tmp95 = std::sin(_tmp94);
  const Scalar _tmp96 = std::sin(_tmp90);
  const Scalar _tmp97 = _tmp11 * _tmp96;
  const Scalar _tmp98 = _tmp95 * _tmp97;
  const Scalar _tmp99 = _tmp93 - _tmp98;
  const Scalar _tmp100 = std::cos(_tmp94);
  const Scalar _tmp101 = _tmp100 * _tmp96;
  const Scalar _tmp102 = _tmp15 * std::cos(_tmp84);
  const Scalar _tmp103 = _tmp95 * _tmp96;
  const Scalar _tmp104 = -_tmp101 * _tmp92 + _tmp102 * _tmp103;
  const Scalar _tmp105 = _tmp10 * (_tmp102 * _tmp104 - _tmp11 * _tmp99);
  const Scalar _tmp106 = _tmp10 * _tmp99;
  const Scalar _tmp107 = _tmp105 + _tmp106;
  const Scalar _tmp108 = _tmp102 * _tmp91;
  const Scalar _tmp109 = _tmp100 * _tmp97;
  const Scalar _tmp110 = -_tmp108 + _tmp109;
  const Scalar _tmp111 = _tmp10 * (-_tmp104 * _tmp92 + _tmp11 * _tmp110);
  const Scalar _tmp112 = _tmp10 * _tmp110;
  const Scalar _tmp113 = _tmp11 + _tmp112;
  const Scalar _tmp114 = _tmp111 + _tmp113;
  const Scalar _tmp115 =
      -std::max<Scalar>(_tmp11, std::max<Scalar>(_tmp111, std::max<Scalar>(_tmp112, _tmp114)));
  const Scalar _tmp116 = _tmp111 + _tmp115;
  const Scalar _tmp117 = 1 - std::max<Scalar>(0, -(((_tmp116) > 0) - ((_tmp116) < 0)));
  const Scalar _tmp118 = std::min<Scalar>(
      1 - std::max<Scalar>(0, _tmp117),
      1 - std::max<Scalar>(0, -(((_tmp112 + _tmp115) > 0) - ((_tmp112 + _tmp115) < 0))));
  const Scalar _tmp119 = -_tmp111;
  const Scalar _tmp120 = _tmp112 + _tmp119 + _tmp49;
  const Scalar _tmp121 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp120)));
  const Scalar _tmp122 = -_tmp118 + _tmp121 + 1;
  const Scalar _tmp123 = (Scalar(1) / Scalar(2)) * _tmp118;
  const Scalar _tmp124 = _tmp123 / _tmp122;
  const Scalar _tmp125 = 1 - _tmp112;
  const Scalar _tmp126 = _tmp111 + _tmp125 + _tmp48;
  const Scalar _tmp127 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp126)));
  const Scalar _tmp128 = -_tmp117 + _tmp127 + 1;
  const Scalar _tmp129 = (Scalar(1) / Scalar(2)) * _tmp117;
  const Scalar _tmp130 = _tmp10 * (-_tmp102 * _tmp110 + _tmp92 * _tmp99);
  const Scalar _tmp131 = _tmp102 + _tmp130;
  const Scalar _tmp132 = std::min<Scalar>(
      1 - std::max<Scalar>(0, std::max<Scalar>(_tmp117, _tmp118)),
      1 - std::max<Scalar>(0, -(((_tmp11 + _tmp115) > 0) - ((_tmp11 + _tmp115) < 0))));
  const Scalar _tmp133 = _tmp11 + _tmp119 + _tmp125;
  const Scalar _tmp134 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp133)));
  const Scalar _tmp135 = -_tmp132 + _tmp134 + 1;
  const Scalar _tmp136 = (Scalar(1) / Scalar(2)) * _tmp132;
  const Scalar _tmp137 = _tmp136 / _tmp135;
  const Scalar _tmp138 = _tmp10 * _tmp104;
  const Scalar _tmp139 = -_tmp138 + _tmp92;
  const Scalar _tmp140 = std::min<Scalar>(
      1 - std::max<Scalar>(0, std::max<Scalar>(_tmp117, std::max<Scalar>(_tmp118, _tmp132))),
      1 - std::max<Scalar>(0, -(((_tmp113 + _tmp116) > 0) - ((_tmp113 + _tmp116) < 0))));
  const Scalar _tmp141 = _tmp114 + 1;
  const Scalar _tmp142 = std::sqrt(Scalar(std::max<Scalar>(0, _tmp141)));
  const Scalar _tmp143 = -_tmp140 + _tmp142 + 1;
  const Scalar _tmp144 = (Scalar(1) / Scalar(2)) * _tmp140;
  const Scalar _tmp145 = _tmp144 / _tmp143;
  const Scalar _tmp146 =
      _tmp107 * _tmp124 + _tmp128 * _tmp129 + _tmp131 * _tmp137 + _tmp139 * _tmp145;
  const Scalar _tmp147 = _tmp74 / _tmp73;
  const Scalar _tmp148 = -_tmp39 + _tmp40;
  const Scalar _tmp149 = _tmp26 + _tmp61;
  const Scalar _tmp150 = _tmp147 * _tmp76 + _tmp148 * _tmp69 + _tmp149 * _tmp60 + _tmp79 * _tmp80;
  const Scalar _tmp151 = _tmp138 + _tmp92;
  const Scalar _tmp152 = _tmp129 / _tmp128;
  const Scalar _tmp153 = -_tmp105 + _tmp106;
  const Scalar _tmp154 =
      _tmp124 * _tmp151 + _tmp131 * _tmp152 + _tmp135 * _tmp136 + _tmp145 * _tmp153;
  const Scalar _tmp155 = -_tmp102 + _tmp130;
  const Scalar _tmp156 =
      _tmp107 * _tmp152 + _tmp122 * _tmp123 + _tmp137 * _tmp151 + _tmp145 * _tmp155;
  const Scalar _tmp157 = -_tmp36 + _tmp75;
  const Scalar _tmp158 = _tmp147 * _tmp41 + _tmp149 * _tmp81 + _tmp157 * _tmp69 + _tmp58 * _tmp59;
  const Scalar _tmp159 =
      _tmp124 * _tmp155 + _tmp137 * _tmp153 + _tmp139 * _tmp152 + _tmp143 * _tmp144;
  const Scalar _tmp160 = _tmp147 * _tmp62 + _tmp148 * _tmp81 + _tmp157 * _tmp60 + _tmp67 * _tmp68;
  const Scalar _tmp161 =
      _tmp146 * _tmp82 + _tmp150 * _tmp154 + _tmp156 * _tmp158 + _tmp159 * _tmp160;
  const Scalar _tmp162 = _RotHandEye[0] * _tmp5 + _RotHandEye[1] * _tmp4 - _RotHandEye[2] * _tmp6 +
                         _RotHandEye[3] * _tmp7;
  const Scalar _tmp163 =
      -_tmp146 * _tmp158 + _tmp150 * _tmp159 - _tmp154 * _tmp160 + _tmp156 * _tmp82;
  const Scalar _tmp164 =
      -_tmp146 * _tmp160 - _tmp150 * _tmp156 + _tmp154 * _tmp158 + _tmp159 * _tmp82;
  const Scalar _tmp165 = -_RotHandEye[0] * _tmp6 - _RotHandEye[1] * _tmp7 - _RotHandEye[2] * _tmp5 +
                         _RotHandEye[3] * _tmp4;
  const Scalar _tmp166 = -_RotHandEye[0] * _tmp7 + _RotHandEye[1] * _tmp6 + _RotHandEye[2] * _tmp4 +
                         _RotHandEye[3] * _tmp5;
  const Scalar _tmp167 =
      _tmp146 * _tmp150 - _tmp154 * _tmp82 - _tmp156 * _tmp160 + _tmp158 * _tmp159;
  const Scalar _tmp168 =
      -_tmp161 * _tmp8 - _tmp162 * _tmp163 + _tmp164 * _tmp165 + _tmp166 * _tmp167;
  const Scalar _tmp169 = -_tmp162 * _tmp167 - _tmp163 * _tmp166 - _tmp164 * _tmp8;
  const Scalar _tmp170 = _tmp161 * _tmp165;
  const Scalar _tmp171 = _tmp169 - _tmp170;
  const Scalar _tmp172 = std::fabs(_tmp171);
  const Scalar _tmp173 = 1 - epsilon;
  const Scalar _tmp174 = (Scalar(1) / Scalar(2)) * _tmp16;
  const Scalar _tmp175 = (Scalar(1) / Scalar(2)) * _tmp15;
  const Scalar _tmp176 = std::pow(_tmp12, Scalar(-2));
  const Scalar _tmp177 = 2 * _tmp13;
  const Scalar _tmp178 = _tmp177 * (_tmp174 * _tmp86 * _tmp88 / _tmp87 + _tmp175 * _tmp86) /
                         (_tmp176 * std::pow(_tmp89, Scalar(2)) + 1);
  const Scalar _tmp179 = _tmp178 * _tmp95;
  const Scalar _tmp180 = _tmp100 * _tmp178;
  const Scalar _tmp181 = (Scalar(1) / Scalar(2)) * _tmp101 * _tmp102 +
                         (Scalar(1) / Scalar(2)) * _tmp103 * _tmp92 + _tmp108 * _tmp179 -
                         _tmp180 * _tmp93;
  const Scalar _tmp182 = _tmp178 * _tmp96;
  const Scalar _tmp183 = _tmp11 * _tmp91;
  const Scalar _tmp184 = _tmp102 * _tmp182 + _tmp180 * _tmp183 - Scalar(1) / Scalar(2) * _tmp98;
  const Scalar _tmp185 = _tmp10 * (_tmp11 * _tmp184 - _tmp181 * _tmp92);
  const Scalar _tmp186 = -_tmp185;
  const Scalar _tmp187 = _tmp10 * _tmp184;
  const Scalar _tmp188 = (Scalar(1) / Scalar(8)) * _tmp118 * (_tmp186 + _tmp187) *
                         ((((_tmp120) > 0) - ((_tmp120) < 0)) + 1) / _tmp121;
  const Scalar _tmp189 = _tmp188 / std::pow(_tmp122, Scalar(2));
  const Scalar _tmp190 = _tmp10 * _tmp181;
  const Scalar _tmp191 = -Scalar(1) / Scalar(2) * _tmp109 - _tmp179 * _tmp183 - _tmp182 * _tmp92;
  const Scalar _tmp192 = _tmp10 * (_tmp102 * _tmp181 - _tmp11 * _tmp191);
  const Scalar _tmp193 = _tmp10 * _tmp191;
  const Scalar _tmp194 = -_tmp192 + _tmp193;
  const Scalar _tmp195 = _tmp10 * (-_tmp102 * _tmp184 + _tmp191 * _tmp92);
  const Scalar _tmp196 = -_tmp187;
  const Scalar _tmp197 = (Scalar(1) / Scalar(8)) * _tmp132 * (_tmp186 + _tmp196) *
                         ((((_tmp133) > 0) - ((_tmp133) < 0)) + 1) / _tmp134;
  const Scalar _tmp198 = (Scalar(1) / Scalar(8)) * _tmp117 * (_tmp185 + _tmp196) *
                         ((((_tmp126) > 0) - ((_tmp126) < 0)) + 1) / _tmp127;
  const Scalar _tmp199 = _tmp198 / std::pow(_tmp128, Scalar(2));
  const Scalar _tmp200 = (Scalar(1) / Scalar(8)) * _tmp140 * (_tmp185 + _tmp187) *
                         ((((_tmp141) > 0) - ((_tmp141) < 0)) + 1) / _tmp142;
  const Scalar _tmp201 = _tmp200 / std::pow(_tmp143, Scalar(2));
  const Scalar _tmp202 = _tmp124 * _tmp190 - _tmp131 * _tmp199 + _tmp145 * _tmp194 -
                         _tmp151 * _tmp189 + _tmp152 * _tmp195 - _tmp153 * _tmp201 + _tmp197;
  const Scalar _tmp203 = _tmp197 / std::pow(_tmp135, Scalar(2));
  const Scalar _tmp204 = _tmp192 + _tmp193;
  const Scalar _tmp205 = -_tmp107 * _tmp189 + _tmp124 * _tmp204 - _tmp131 * _tmp203 +
                         _tmp137 * _tmp195 - _tmp139 * _tmp201 - _tmp145 * _tmp190 + _tmp198;
  const Scalar _tmp206 = _tmp177 * (_tmp174 * _tmp20 * _tmp22 / _tmp21 + _tmp175 * _tmp20) /
                         (_tmp176 * std::pow(_tmp23, Scalar(2)) + 1);
  const Scalar _tmp207 = _tmp206 * _tmp34;
  const Scalar _tmp208 = _tmp206 * _tmp29;
  const Scalar _tmp209 = -_tmp207 * _tmp27 + _tmp208 * _tmp42 +
                         (Scalar(1) / Scalar(2)) * _tmp29 * _tmp35 +
                         (Scalar(1) / Scalar(2)) * _tmp34 * _tmp37;
  const Scalar _tmp210 = _tmp10 * _tmp209;
  const Scalar _tmp211 = _tmp11 * _tmp25;
  const Scalar _tmp212 = -_tmp206 * _tmp35 - _tmp208 * _tmp211 - Scalar(1) / Scalar(2) * _tmp43;
  const Scalar _tmp213 = _tmp10 * _tmp212;
  const Scalar _tmp214 = _tmp10 * (-_tmp11 * _tmp212 + _tmp209 * _tmp36);
  const Scalar _tmp215 = _tmp213 - _tmp214;
  const Scalar _tmp216 = _tmp206 * _tmp37 + _tmp207 * _tmp211 - Scalar(1) / Scalar(2) * _tmp32;
  const Scalar _tmp217 = _tmp10 * _tmp216;
  const Scalar _tmp218 = -_tmp217;
  const Scalar _tmp219 = _tmp10 * (_tmp11 * _tmp216 - _tmp209 * _tmp26);
  const Scalar _tmp220 = (Scalar(1) / Scalar(8)) * _tmp55 * (_tmp218 + _tmp219) *
                         ((((_tmp71) > 0) - ((_tmp71) < 0)) + 1) / _tmp72;
  const Scalar _tmp221 = _tmp220 / std::pow(_tmp73, Scalar(2));
  const Scalar _tmp222 = -_tmp219;
  const Scalar _tmp223 = (Scalar(1) / Scalar(8)) * _tmp57 * (_tmp217 + _tmp222) *
                         ((((_tmp50) > 0) - ((_tmp50) < 0)) + 1) / _tmp51;
  const Scalar _tmp224 = _tmp223 / std::pow(_tmp58, Scalar(2));
  const Scalar _tmp225 = _tmp212 * _tmp26 - _tmp216 * _tmp36;
  const Scalar _tmp226 = _tmp10 * _tmp60;
  const Scalar _tmp227 = (Scalar(1) / Scalar(8)) * _tmp66 * (_tmp217 + _tmp219) *
                         ((((_tmp63) > 0) - ((_tmp63) < 0)) + 1) / _tmp64;
  const Scalar _tmp228 = (Scalar(1) / Scalar(8)) * _tmp65 * (_tmp218 + _tmp222) *
                         ((((_tmp77) > 0) - ((_tmp77) < 0)) + 1) / _tmp78;
  const Scalar _tmp229 = _tmp228 / std::pow(_tmp79, Scalar(2));
  const Scalar _tmp230 = -_tmp147 * _tmp210 - _tmp148 * _tmp229 - _tmp157 * _tmp224 +
                         _tmp215 * _tmp81 - _tmp221 * _tmp62 + _tmp225 * _tmp226 + _tmp227;
  const Scalar _tmp231 = _tmp227 / std::pow(_tmp67, Scalar(2));
  const Scalar _tmp232 = _tmp10 * _tmp225;
  const Scalar _tmp233 = _tmp147 * _tmp232 - _tmp148 * _tmp231 - _tmp149 * _tmp224 +
                         _tmp209 * _tmp226 + _tmp215 * _tmp69 - _tmp221 * _tmp76 + _tmp228;
  const Scalar _tmp234 = -_tmp107 * _tmp199 + _tmp137 * _tmp190 + _tmp145 * _tmp195 -
                         _tmp151 * _tmp203 + _tmp152 * _tmp204 - _tmp155 * _tmp201 + _tmp188;
  const Scalar _tmp235 = _tmp213 + _tmp214;
  const Scalar _tmp236 = _tmp10 * _tmp69;
  const Scalar _tmp237 = -_tmp209 * _tmp236 + _tmp220 - _tmp224 * _tmp41 - _tmp229 * _tmp76 -
                         _tmp231 * _tmp62 + _tmp232 * _tmp81 + _tmp235 * _tmp60;
  const Scalar _tmp238 = _tmp147 * _tmp235 - _tmp149 * _tmp229 - _tmp157 * _tmp231 +
                         _tmp210 * _tmp81 - _tmp221 * _tmp41 + _tmp223 + _tmp225 * _tmp236;
  const Scalar _tmp239 = _tmp124 * _tmp195 + _tmp137 * _tmp194 - _tmp139 * _tmp199 -
                         _tmp152 * _tmp190 - _tmp153 * _tmp203 - _tmp155 * _tmp189 + _tmp200;
  const Scalar _tmp240 = -_tmp146 * _tmp230 - _tmp150 * _tmp234 + _tmp154 * _tmp238 -
                         _tmp156 * _tmp233 + _tmp158 * _tmp202 + _tmp159 * _tmp237 -
                         _tmp160 * _tmp205 + _tmp239 * _tmp82;
  const Scalar _tmp241 = _tmp146 * _tmp233 + _tmp150 * _tmp205 - _tmp154 * _tmp237 -
                         _tmp156 * _tmp230 + _tmp158 * _tmp239 + _tmp159 * _tmp238 -
                         _tmp160 * _tmp234 - _tmp202 * _tmp82;
  const Scalar _tmp242 = -_tmp146 * _tmp238 + _tmp150 * _tmp239 - _tmp154 * _tmp230 +
                         _tmp156 * _tmp237 - _tmp158 * _tmp205 + _tmp159 * _tmp233 -
                         _tmp160 * _tmp202 + _tmp234 * _tmp82;
  const Scalar _tmp243 = _tmp146 * _tmp237 + _tmp150 * _tmp202 + _tmp154 * _tmp233 +
                         _tmp156 * _tmp238 + _tmp158 * _tmp234 + _tmp159 * _tmp230 +
                         _tmp160 * _tmp239 + _tmp205 * _tmp82;
  const Scalar _tmp244 =
      ((((-_tmp172 + _tmp173) > 0) - ((-_tmp172 + _tmp173) < 0)) + 1) *
      (-_tmp162 * _tmp241 - _tmp165 * _tmp243 - _tmp166 * _tmp242 - _tmp240 * _tmp8) *
      (((_tmp171) > 0) - ((_tmp171) < 0));
  const Scalar _tmp245 =
      2 * std::min<Scalar>(0, (((-_tmp169 + _tmp170) > 0) - ((-_tmp169 + _tmp170) < 0))) + 1;
  const Scalar _tmp246 = std::min<Scalar>(_tmp172, _tmp173);
  const Scalar _tmp247 = 1 - std::pow(_tmp246, Scalar(2));
  const Scalar _tmp248 = _tmp245 / _tmp247;
  const Scalar _tmp249 = _tmp244 * _tmp248;
  const Scalar _tmp250 = _tmp245 * std::acos(_tmp246);
  const Scalar _tmp251 = 2 * _tmp250 / std::sqrt(_tmp247);
  const Scalar _tmp252 = _tmp246 * _tmp250 / (_tmp247 * std::sqrt(_tmp247));
  const Scalar _tmp253 = _tmp244 * _tmp252;
  const Scalar _tmp254 =
      -_tmp161 * _tmp162 + _tmp163 * _tmp8 - _tmp164 * _tmp166 + _tmp165 * _tmp167;
  const Scalar _tmp255 =
      _tmp244 * (-_tmp161 * _tmp166 + _tmp162 * _tmp164 + _tmp163 * _tmp165 - _tmp167 * _tmp8);

  // Output terms (1)
  Eigen::Matrix<Scalar, 3, 1> _res;

  _res(0, 0) =
      -_tmp168 * _tmp249 + _tmp168 * _tmp253 +
      _tmp251 * (-_tmp162 * _tmp242 + _tmp165 * _tmp240 + _tmp166 * _tmp241 - _tmp243 * _tmp8);
  _res(1, 0) =
      -_tmp249 * _tmp254 +
      _tmp251 * (-_tmp162 * _tmp243 + _tmp165 * _tmp241 - _tmp166 * _tmp240 + _tmp242 * _tmp8) +
      _tmp253 * _tmp254;
  _res(2, 0) =
      -_tmp248 * _tmp255 +
      _tmp251 * (_tmp162 * _tmp240 + _tmp165 * _tmp242 - _tmp166 * _tmp243 - _tmp241 * _tmp8) +
      _tmp252 * _tmp255;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
